### ISSUE TITLE
Error: found unexpected type for label 'xxx' (should be array of config options)

### ISSUE THREAD

**Issue by HorizonNet** [actions/labeler#712]
**Description:**
After upgrading to v5.0.0 and changing the labeler configuration file matching to what is outlined in the [documentation](https://github.com/actions/labeler/tree/main#pull-request-labeler), I'm receiving the following error as soon as the action starts

```
Run actions/labeler@v5.0.0
The configuration file (path: .github/labeler.yml) was not found locally, fetching via the api
Error: Error: found unexpected type for label 'terraform' (should be array of config options)
Error: found unexpected type for label 'terraform' (should be array of config options)
```

**Action version:**
5.0.0

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
After upgrading to 5.0.0 changed the labeler configuration to

```yaml
terraform:
  - changed-files:
    - any-glob-to-any-file: terraform/**
 ```

which to me looks similar to the example from the documentation

```yaml
Documentation:
- changed-files:
  - any-glob-to-any-file: docs/*
```

The workflow is defined as follows and used to work previously

```yaml
---
name: Pull Request Labeler

on:
  pull_request_target:

jobs:
  triage:
    name: Label triage

    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/labeler@v5.0.0
        with:
          sync-labels: true
```

**Expected behavior:**
The action should run successfully.

**Actual behavior:**
The action is failing with the error provided above.

**Comment by MaksimZhukov** [comment]
Hello @HorizonNet!
Thank you for reporting this! 
We will take a look and contact you as soon as we have any updates!

**Comment by PartTimeLegend** [comment]
I'm having the same issue.

My config looks like this.

```github:
- changed-files:
  - any-glob-to-any-file: .github/*
mergify:
- changed-files:
  - any-glob-to-any-file: .mergify.yml
docker:
- changed-files:
  - any-glob-to-any-file: Dockerfile
license:
- changed-files:
  - any-glob-to-any-file: LICENSE
windows:
- changed-files:
  - any-glob-to-any-file: NewMachineSetup.ps1
  - any-glob-to-any-file: chocolatey.txt
  - any-glob-to-any-file: features.txt
mac:
- changed-files:
  - any-glob-to-any-file: NewMachineSetup.sh
  - any-glob-to-any-file: brews.txt
docs:
- changed-files:
  - any-glob-to-any-file: README.md
  - any-glob-to-any-file: SECURITY.md
python:
- changed-files:
  - any-glob-to-any-file: requirements.txt```

**Comment by MaksimZhukov** [comment]
@HorizonNet could you please provide us with a link to the public repository where the issue occurs? 
I could not reproduce your issue. I used the [workflow](https://github.com/MaksimZhukov/config-issue/blob/main/.github/workflows/config-issue.yml) and [configuration](https://github.com/MaksimZhukov/config-issue/blob/main/.github/labeler.yml) files that you provided, but everything works as expected (link to the [related PR](https://github.com/MaksimZhukov/config-issue/pull/1)).

**Comment by bryannaegele** [comment]
@MaksimZhukov we have this issue with labels in the format of `abc/def` on internal repos and snake case on some public ones.

[Failed public run](https://github.com/open-telemetry/opentelemetry-erlang-contrib/actions/runs/7168661279/job/19517329790?pr=233)
[Labeler Config](https://github.com/open-telemetry/opentelemetry-erlang-contrib/blob/main/.github/labeler.yml)
[Workflow](https://github.com/open-telemetry/opentelemetry-erlang-contrib/blob/main/.github/workflows/labeler.yml)

**Comment by bryannaegele** [comment]
I don't know if it's just some yaml parsing strictness that's changed. That's all I can think of

**Comment by MaksimZhukov** [comment]
@bryannaegele you see the error because the configuration file structure was significantly redesigned and is not compatible with the structure of the previous version. Please read the [action documentation](https://github.com/actions/labeler#pull-request-labeler) to find out how to adapt your configuration files for use with the new action version

**Comment by bryannaegele** [comment]
Oh, wow. I didn't see that. That's a significant change. Noted. 👍🏻

**Comment by mndeveci** [comment]
@MaksimZhukov we are having the same issue as well. Does both action version and its configuration be up to date in the develop/main branch for this to work?

[This was my attempt to update configuration](https://github.com/aws/aws-sam-cli/pull/6411), [but GHA is still failing](https://github.com/aws/aws-sam-cli/actions/runs/7122709971)
```
apply-file-based-labels
Error: found unexpected type for label 'area/package' (should be array of config options)
```

**Comment by lamdor** [comment]
I've also ran into the same issue, but I'm not sure what is correct. The README refers to lists of globs, however, the examples show only a string and not a list. And then the config on https://github.com/actions/labeler/issues/712#issuecomment-1846852430 shows multiple items with `any-glob-to-any-file`. It's confusing.

**Comment by MaksimZhukov** [comment]
Hello @mndeveci! I am using your [configuration file](https://github.com/MaksimZhukov/config-issue/blob/main/.github/labeler2.yml) and it works ([workflow run](https://github.com/MaksimZhukov/config-issue/actions/runs/7172431910/job/19529637494#step:2:30), [related PR](https://github.com/MaksimZhukov/config-issue/pull/2)). Could you please check?

Hello @lamdor! Thank you for your comment! We will add more examples to the documentation!

**Comment by tautschnig** [comment]
> @MaksimZhukov we are having the same issue as well. Does both action version and its configuration be up to date in the develop/main branch for this to work?
> 

Let me echo the above question: which action and labeling configuration files are used upon a run, the ones from the base branch or the ones from the head branch? https://github.com/model-checking/kani/pull/2923 (with GitHub action log https://github.com/model-checking/kani/actions/runs/7131018587/job/19418690999) was my attempt to downgrade to v4, but it would still fail with this error message?! Are we perhaps just facing a transient issue in that we need to accept the failure in the PR that upgrades the config file, and all will be well afterwards?

**Comment by bryannaegele** [comment]
@tautschnig `pull_request_target` event trigger uses the default branch.

**Comment by fballiano** [comment]
In OpenMage we can't seem to make it work https://github.com/OpenMage/magento-lts/pull/3695 :-(

**Comment by HorizonNet** [comment]
> @HorizonNet could you please provide us with a link to the public repository where the issue occurs? I could not reproduce your issue. I used the [workflow](https://github.com/MaksimZhukov/config-issue/blob/main/.github/workflows/config-issue.yml) and [configuration](https://github.com/MaksimZhukov/config-issue/blob/main/.github/labeler.yml) files that you provided, but everything works as expected (link to the [related PR](https://github.com/MaksimZhukov/config-issue/pull/1)).

@MaksimZhukov I think I found the root cause of the overall problem. I created a [public repository and a PR](https://github.com/HorizonNet/labeler-712/pull/1) to verify the behavior on a fresh repository ([workflow](https://github.com/HorizonNet/labeler-712/blob/main/.github/workflows/pull-request-labeler.yml) & [configuration](https://github.com/HorizonNet/labeler-712/blob/main/.github/labeler.yml)). This one ran fine. Based on that I looked into our private repositories. We have branch protection with a few rules enabled in place, leading to the situation that Dependabot updated the version of the labeler Action (coming from the default branch, the appropriate run ended up fine due to the previous version), but prevented me from updating the necessary configuration. I had to bypass branch protection to get the updated configuration into our main branch. Afterwards the Action started to work as expected again.

Probably the important point here is what @bryannaegele mentioned, meaning that if ```pull_request_target``` is used the configuration needs to be on the default branch already.

**Comment by mndeveci** [comment]
> Hello @mndeveci! I am using your [configuration file](https://github.com/MaksimZhukov/config-issue/blob/main/.github/labeler2.yml) and it works ([workflow run](https://github.com/MaksimZhukov/config-issue/actions/runs/7172431910/job/19529637494#step:2:30), [related PR](https://github.com/MaksimZhukov/config-issue/pull/2)). Could you please check?

Thanks for confirming behaviour @MaksimZhukov. With the comment above from @HorizonNet, I think it is clear that both GHA version and its configuration must be up to date in the default branch this to work. So we should either update configuration in the PR where labeler is version bumped, or that particular PR should be merged with discarding failures and follow-up PRs should succeed since they will be using up to date configuration and newer version there.

**Comment by Borda** [comment]
> @tautschnig `pull_request_target` event trigger uses the default branch.

Yes, for the action, but not for the config, correct?

**Comment by HorizonNet** [comment]
> > @tautschnig `pull_request_target` event trigger uses the default branch.
> 
> Yes, for the action, but not for the config, correct?

@Borda Based on my tests and what I've seen so far, also the config needs to be in the default branch.

**Comment by Borda** [comment]
We have just updated the action in https://github.com/Lightning-AI/pytorch-lightning/pull/19135, and as mentioned as suggested, usage is with `pull_request_target`; you do not see the eventual config breakage until you merge it and suddenly, all is going wrong and affecting everyone :confused: 

Also, with o open, update the config in https://github.com/Lightning-AI/pytorch-lightning/pull/19151 I still see the action crashing even when we follow the basic example
```yaml
app:
  - changed-files:
      - any-glob-to-any-file:
          - "src/lightning/app/**"
          - "src/lightning_app/*"
          - "tests/tests_app/**"
...
```
with the [message](https://github.com/Lightning-AI/pytorch-lightning/actions/runs/7192614118/job/19589386504?pr=19151):
```
The configuration file (path: .github/label-change.yml) was not found locally, fetching via the api
Error: Error: found unexpected type for label 'app' (should be array of config options)
Error: found unexpected type for label 'app' (should be array of config options)
```

**Comment by Borda** [comment]
> @Borda Based on my tests and what I've seen so far, also the config needs to be in the default branch.

so it means that for debugging we need to temporally switch to the `pull_request` and before merging revert to `pull_request_target`

**Comment by HorizonNet** [comment]
> > @Borda Based on my tests and what I've seen so far, also the config needs to be in the default branch.
> 
> so it means that for debugging we need to temporally switch to the `pull_request` and before merging revert to `pull_request_target`

Can't tell as I haven't switched the trigger. In my case it was easier/better to bypass branch protection once.

**Comment by FranzForstmayr** [comment]
I missed the `checkout` action (https://github.com/scikit-rf/scikit-rf/blob/06190acd59d7be77e7907b45456ffecba66dfd1d/.github/workflows/PR_labeler.yml#L9) in our configuration yml file before, that's why the old labeler.yml file was used all the time.

```
The configuration file (path: .github/labeler.yml) was not found locally, fetching via the api
```

So I ended up deleting the whole workflow (https://github.com/scikit-rf/scikit-rf/pull/985), labeler still failed as there was no checkout task. After merging to master I re enabled the PR labeler from scratch (https://github.com/scikit-rf/scikit-rf/pull/986).

**Comment by bryannaegele** [comment]
Depending on what your workflows do based on labels, I suggest not permanently using checkout and using what is in the head branch to prevent PRs from causing issues or opening up potential abuse.

**Comment by CatChen** [comment]
I had the same issue. I created a PR that migrates the config from v4 format to v5 format. I changed the triggering event from `pull_request_target` to `pull_request` but the job still failed. This resolved my issue but I can't explain why: add `- uses: actions/checkout@v4` before `- uses: actions/labeler@v5` in the config migration PR.

In theory, using the `pull_request` event should be enough and checkout isn't needed. `actions/labeler@v5` prints out `The configuration file (path: .github/labeler.yml) was not found locally, fetching via the api` and it should fetch the updated config from the PR's head (instead of base, which usually means `main`). Adding checkout changes that printout to `The configuration file (path: .github/labeler.yml) was found locally, reading from the file` and it magically fixed my issue.

After a successful run, removing `actions/checkout@v4` doesn't break it. That's really weird.

I looked into the implementation of [how `actions/labeler@v5` fetches the config from remote](https://github.com/actions/labeler/blob/17086b774338d2689ada0d8fcc8c51b5c9bc782a/src/api/get-content.ts#L12) and everything looks fine to me. I don't plan to spend more time on this investigation. Maybe this information can help others.

**Comment by IvanZosimov** [comment]
Hi, all! Thanks for drawing our attention to the issue ❤️ , recently we've merged [PR](https://github.com/actions/labeler/pull/721) that should clarify the cause of the problem, provide mitigation plan and help to make process of migration clearer. I'm going to close this issue, if you have any additional questions feel free to reach out.

**Comment by oerp-odoo** [comment]
After switching from v4 to v5 labeler, it does not seem to be stable and consistent.

Now labeler action randomly fails with:

`Error: found unexpected type for label 'documentation' (should be array of config options)`

Strangely if I re-run same failed job, it then passes. And most of the time it passes first time, but sometimes just fails randomly with that error..

workflow looks like this:

```yaml
name: Labeler
on:
  - pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: [self-hosted, pool]
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
```

Config:

```yaml
---
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**/*
          - README.rst
ops:
  - changed-files:
      - any-glob-to-any-file:
          - ops/**/*
          - .github/**/*
dev:
  - changed-files:
      - any-glob-to-any-file:
          - src/**/*
```

P.S. v4 had no such problems.

**Comment by BillyBlaze** [comment]
After changing `pull_request_target` to `pull_request` and some further investigation I was able to fix this, the problem is that it was still using the config v4 file from the base branch, I fixed this in the PR by adding a checkout. After confirming everything worked in my PR I removed the checkout and reverted `pull_request` to `pull_request_target`

```
      - uses: actions/checkout@v4
        with:
          clean: false
          ref: ${{ github.event.pull_request.head.sha }}
```

**Comment by onkar** [comment]
I am still seeing this issue. Here is what I have:

File `.github/labeler.yml`:
```
migrations:
  - changed-files:
    - any-glob-to-any-file: dir1/dir2/group_loader.py
    - any-glob-to-any-file: dir1/dir2/groups.py
    - any-glob-to-any-file: dir1/dir3/**/*
    - any-glob-to-any-file: dir1/dir2/xyz/*
```

File `.github/workflows/labeler.yml`:
```
name: "Pull Request Labeler"
on:
- pull_request

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        clean: false
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
```

But I see the following error:
```
Run actions/labeler@v5
  with:
    repo-token: ***
    configuration-path: .github/labeler.yml
    sync-labels: false
    dot: true
The configuration file (path: .github/labeler.yml) was found locally, reading from the file
Error: Error: found unexpected type for label 'migrations' (should be array of config options)
Error: found unexpected type for label 'migrations' (should be array of config options)
```

Any idea how to fix this?
